#!/bin/sh
PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin

cp /home/pi/AssistantFVL/asoundrc /home/pi/.asoundrc
sudo cp /home/pi/AssistantFVL/asoundrc /root/.asoundrc
sudo echo "runned script" >> /home/pi/run.txt
sudo cat /media/pi/PACIENTE/wifi >> /etc/wpa_supplicant/wpa_supplicant.conf
sleep 1
sudo wpa_cli -i wlan0 reconfigure
sleep 2
sudo service networking restart
sleep 1 
sudo service networking restart
sudo python3 /home/pi/AssistantFVL/button4.py &
exit 0
